# Generated by Django 5.1.7 on 2026-04-28 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
